module Skia.Bindings.Internal.Helper where

import Foreign.C.Types
import Skia.Bindings.Internal.AutoGenerated

foreign import ccall "hsskia.hpp" hsskia_SkColorTypeBytesPerPixel :: Sk_colortype -> IO CInt
foreign import ccall "hsskia.hpp" hsskia_SkColorTypeIsAlwaysOpaque :: Sk_colortype -> IO CBool